// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PollChallenge.Model.Data;

namespace PollChallenge.Model.Migrations
{
    [DbContext(typeof(PollDbContext))]
    partial class PollDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6");

            modelBuilder.Entity("PollChallenge.Model.Entities.Option", b =>
                {
                    b.Property<int>("poll_id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id")
                        .HasColumnName("option_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnName("description")
                        .HasColumnType("TEXT");

                    b.Property<long>("VotesQty")
                        .HasColumnName("votes_qty")
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L);

                    b.HasKey("poll_id", "Id");

                    b.ToTable("tb_option");
                });

            modelBuilder.Entity("PollChallenge.Model.Entities.Poll", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("poll_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnName("description")
                        .HasColumnType("TEXT");

                    b.Property<long>("ViewsQty")
                        .HasColumnName("views_qty")
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L);

                    b.HasKey("Id");

                    b.ToTable("tb_poll");
                });

            modelBuilder.Entity("PollChallenge.Model.Entities.Option", b =>
                {
                    b.HasOne("PollChallenge.Model.Entities.Poll", "Poll")
                        .WithMany("Options")
                        .HasForeignKey("poll_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
